//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFfirst
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    //EF 访问数据库的上下文：知道访问数据库的所有内容
    public partial class JoinSoft_JYBZEntities : DbContext
    {
        public JoinSoft_JYBZEntities()
            : base("name=JoinSoft_JYBZEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<GY_EMP> GY_EMP { get; set; }
        public DbSet<GY_ITEM> GY_ITEM { get; set; }
    }
}
