//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFfirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class GY_EMP
    {
        public string id { get; set; }
        public string CLASSIFICATION { get; set; }
        public string KEYED_NAME { get; set; }
        public System.DateTime CREATED_ON { get; set; }
        public string CREATED_BY_ID { get; set; }
        public string OWNED_BY_ID { get; set; }
        public string MANAGED_BY_ID { get; set; }
        public Nullable<System.DateTime> MODIFIED_ON { get; set; }
        public string MODIFIED_BY_ID { get; set; }
        public string CURRENT_STATE { get; set; }
        public string STATE { get; set; }
        public string LOCKED_BY_ID { get; set; }
        public string IS_CURRENT { get; set; }
        public string MAJOR_REV { get; set; }
        public string MINOR_REV { get; set; }
        public string IS_RELEASED { get; set; }
        public string NOT_LOCKABLE { get; set; }
        public string CSS { get; set; }
        public Nullable<int> GENERATION { get; set; }
        public string NEW_VERSION { get; set; }
        public string CONFIG_ID { get; set; }
        public string PERMISSION_ID { get; set; }
        public string TEAM_ID { get; set; }
        public string FNUMBER { get; set; }
        public string FSHORTNUMBER { get; set; }
        public string FNAME { get; set; }
        public string FDETAILID { get; set; }
        public string FGENDER { get; set; }
        public string FDEPTID { get; set; }
        public string FADDRESS { get; set; }
        public Nullable<System.DateTime> FHIREDATE { get; set; }
        public Nullable<System.DateTime> FLEAVEDATE { get; set; }
        public string FBANKACCOUNT { get; set; }
        public string FPHONE { get; set; }
        public string FIDCARDID { get; set; }
        public Nullable<System.DateTime> FBIRTHDAY { get; set; }
        public string FBIRTHPLACE { get; set; }
        public string FDEGREE { get; set; }
        public string FDUTY { get; set; }
        public string FDELETED { get; set; }
        public string ISIMPORTFLAG { get; set; }
        public string FNOTE { get; set; }
        public string FOUTERID { get; set; }
        public string FOUTERNUMBER { get; set; }
        public string FOUTERNAME { get; set; }
        public string FWCID { get; set; }
        public string FPARENTID { get; set; }
        public string FPROFESSIONAL { get; set; }
        public string FMANAGER { get; set; }
        public Nullable<int> FORDER { get; set; }
        public string FHOMEPHONE { get; set; }
        public string FFAX { get; set; }
        public string FOFFICEPHONE { get; set; }
        public string FEMAIL { get; set; }
        public string FERPID { get; set; }
        public string FEASID { get; set; }
    }
}
