//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFfirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class GY_ITEM
    {
        public string id { get; set; }
        public string CLASSIFICATION { get; set; }
        public string KEYED_NAME { get; set; }
        public System.DateTime CREATED_ON { get; set; }
        public string CREATED_BY_ID { get; set; }
        public string OWNED_BY_ID { get; set; }
        public string MANAGED_BY_ID { get; set; }
        public Nullable<System.DateTime> MODIFIED_ON { get; set; }
        public string MODIFIED_BY_ID { get; set; }
        public string CURRENT_STATE { get; set; }
        public string STATE { get; set; }
        public string LOCKED_BY_ID { get; set; }
        public string IS_CURRENT { get; set; }
        public string MAJOR_REV { get; set; }
        public string MINOR_REV { get; set; }
        public string IS_RELEASED { get; set; }
        public string NOT_LOCKABLE { get; set; }
        public string CSS { get; set; }
        public Nullable<int> GENERATION { get; set; }
        public string NEW_VERSION { get; set; }
        public string CONFIG_ID { get; set; }
        public string PERMISSION_ID { get; set; }
        public string TEAM_ID { get; set; }
        public string FNUMBER { get; set; }
        public string FSHORTNUMBER { get; set; }
        public string FNAME { get; set; }
        public string FSHORTNAME { get; set; }
        public string FMODEL { get; set; }
        public string FPARENTID { get; set; }
        public string FDETAILID { get; set; }
        public Nullable<decimal> FSECCOEFFICIENT { get; set; }
        public string FDEFAULTSTOCKID { get; set; }
        public Nullable<decimal> FSECINV { get; set; }
        public string FDELETED { get; set; }
        public string FISKFPERIOD { get; set; }
        public Nullable<decimal> FKFPERIOD { get; set; }
        public string FTRACK { get; set; }
        public Nullable<decimal> FPOHIGHPRICE { get; set; }
        public Nullable<decimal> FSOLOWPRC { get; set; }
        public Nullable<int> FQTYDECIMAL { get; set; }
        public string FISSALE { get; set; }
        public string FISEQUIPMENT { get; set; }
        public string FEQUIPMENTNUM { get; set; }
        public Nullable<decimal> FORDERPRICE { get; set; }
        public Nullable<decimal> FSALEPRICE { get; set; }
        public string ISIMPORTFLAG { get; set; }
        public string FEXEMPTION { get; set; }
        public Nullable<decimal> FLEADTIME { get; set; }
        public Nullable<decimal> FFIXLEADTIME { get; set; }
        public string FDEFAULTOUTSTOCKID { get; set; }
        public string FWASTESTOCKID { get; set; }
        public string FDEPT { get; set; }
        public Nullable<decimal> STEELTYPE_MAX { get; set; }
        public Nullable<decimal> FINHIGHLIMIT { get; set; }
        public Nullable<decimal> FLOWBATCHQTY { get; set; }
        public Nullable<decimal> FFEEDLENGTH { get; set; }
        public string FISSERIALNO { get; set; }
        public string FISBATCHNO { get; set; }
        public Nullable<decimal> FGROSSWEIGHT { get; set; }
        public Nullable<decimal> FNETWEIGHT { get; set; }
        public string FOUTERID { get; set; }
        public string FOUTERNUMBER { get; set; }
        public string FOUTERNAME { get; set; }
        public string FPROPERTY { get; set; }
        public string FUNITID { get; set; }
        public string FSECUNITID { get; set; }
        public string FDEFAULTROUTINGID { get; set; }
        public string FMATQUALITY { get; set; }
        public string FDRAWNNO { get; set; }
        public Nullable<decimal> FHIGTHLIMIT { get; set; }
        public Nullable<decimal> FLOWLIMIT { get; set; }
        public string FMAKEDEPT { get; set; }
        public Nullable<int> FRPAIRDATE { get; set; }
        public string FREPAIRDEPT { get; set; }
        public string FSUPPLIER { get; set; }
        public Nullable<System.DateTime> FMODIFYTIME { get; set; }
        public string FSALEACCID { get; set; }
        public Nullable<decimal> FSELPRICE { get; set; }
        public string FITEMINFO { get; set; }
        public string FCHARTNUMBER { get; set; }
        public string FGROUPID { get; set; }
        public Nullable<decimal> FTAXRATE { get; set; }
        public string FISSELLID { get; set; }
        public string FISBATCHNOMANGER { get; set; }
        public string FTEXT { get; set; }
        public string FIMPORTSQE { get; set; }
        public string FACCID { get; set; }
        public string FCOSTACCID { get; set; }
        public string FCOSTDIFFRATE { get; set; }
        public Nullable<int> FCGDATE { get; set; }
        public Nullable<decimal> FWINPRICE { get; set; }
        public string FPACKMODEL { get; set; }
        public string FBZQ { get; set; }
        public Nullable<System.DateTime> FSTARTDATE { get; set; }
        public string FNOTE { get; set; }
        public string FTRIALPRODUCE { get; set; }
        public string FSOURCE { get; set; }
        public string FSPACE { get; set; }
    }
}
