//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFReview
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelFirstDbHmEntities : DbContext
    {
        public ModelFirstDbHmEntities()
            : base("name=ModelFirstDbHmEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Department> Department { get; set; }
        public DbSet<Order> Order { get; set; }
        public DbSet<R_UserInfo_Department> R_UserInfo_Department { get; set; }
        public DbSet<Role> Role { get; set; }
        public DbSet<UserInfo> UserInfo { get; set; }
    }
}
